### ISSUE TITLE
Build breaks with "cannot access org.apache.logging.log4j.spi.LoggerContextShutdownEnabled"

### ISSUE THREAD

**Issue by climategadgets** [climategadgets/jukebox#11]
### Expected Result
Invoking `mvn install` builds the jar file and installs it into `$HOME/.m2`.

### Actual Result
Build fails with the error message below.

Bug report courtesy of TK.

#### mvn install
```
Running net.sf.jukebox.jmx.JmxWrapperTest
Tests run: 18, Failures: 18, Errors: 0, Skipped: 0, Time elapsed: 0.108 sec <<< FAILURE!
warning(junit.framework.TestSuite$1)  Time elapsed: 0.005 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Exception in constructor: testAccessorMutator (java.lang.NoClassDefFoundError: org/apache/logging/log4j/spi/LoggerContextShutdownAware
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.createContextSelector(Log4jContextFactory.java:106)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.<init>(Log4jContextFactory.java:59)

```

#### mvn install -Dmaven.test.skip
```
[ERROR] /home/vt/dev/climategadgets/jukebox/jukebox-service/src/main/java/net/sf/jukebox/service/ApplicationWrapper.java:[132,18] cannot access org.apache.logging.log4j.spi.LoggerContextShutdownEnabled
  class file for org.apache.logging.log4j.spi.LoggerContextShutdownEnabled not found

```

**Comment by climategadgets** [comment]
Root cause: 49082918aa126b4d24f88c47bc1eb67fe586efb3 - dependabot wasn't smart enough to realize there are two dependencies that must have matching versions.
